-- ComplexRepositoryMariaDbIT 전용 최소 스키마. 테이블정의서 8장 DDL 원문 중 이 통합 테스트가 실제로
-- 건드리는 legal_district_code/complex/trade 세 테이블만 재구성한 것이다(TradeChunkLoaderMariaDbIT의
-- trade-race-schema.sql과 내용이 겹치지만, 각 IT 테스트가 자기 스키마를 독립적으로 갖는 이 프로젝트의
-- 관례를 따라 별도 파일로 둔다) — 권위 있는 전체 DDL은 테이블정의서 8장을 그대로 따라야 한다.

CREATE TABLE legal_district_code (
    legal_dong_cd VARCHAR(10) PRIMARY KEY,
    legal_dong_name VARCHAR(60) NOT NULL,
    sido_name VARCHAR(20),
    sigungu_name VARCHAR(20),
    eupmyeondong_name VARCHAR(20),
    is_active BOOLEAN NOT NULL,
    data_version DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE complex (
    complex_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    source_complex_cd VARCHAR(20) NOT NULL UNIQUE,
    legal_dong_cd VARCHAR(10),
    complex_name VARCHAR(100) NOT NULL,
    complex_type VARCHAR(20) NOT NULL,
    sido VARCHAR(20),
    sigungu VARCHAR(20),
    dong_ri VARCHAR(20),
    legal_dong_address VARCHAR(200),
    supply_type VARCHAR(10),
    approval_date DATE,
    building_count SMALLINT,
    household_count INT,
    sale_household_count INT,
    rental_household_count INT,
    public_rental_count INT,
    private_rental_count INT,
    management_type VARCHAR(20),
    heating_type VARCHAR(20),
    corridor_type VARCHAR(20),
    building_structure VARCHAR(30),
    constructor VARCHAR(100),
    developer VARCHAR(100),
    management_company VARCHAR(100),
    elevator_passenger_count SMALLINT NOT NULL,
    elevator_cargo_count SMALLINT NOT NULL,
    elevator_combined_count SMALLINT NOT NULL,
    total_parking_count INT,
    ground_parking_count INT,
    underground_parking_count INT,
    cctv_count SMALLINT,
    home_network_yn BOOLEAN,
    office_address VARCHAR(200),
    office_phone VARCHAR(20),
    community_facilities VARCHAR(500),
    resident_amenities VARCHAR(500),
    highest_floor SMALLINT,
    highest_floor_registered SMALLINT,
    basement_floor_count SMALLINT,
    ev_charger_ground_yn BOOLEAN,
    ev_charger_underground_yn BOOLEAN,
    ev_parking_ground_count SMALLINT,
    ev_parking_underground_count SMALLINT,
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    location_precision VARCHAR(10),
    data_updated_at DATE NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_complex_legal_dong_cd FOREIGN KEY (legal_dong_cd)
        REFERENCES legal_district_code (legal_dong_cd) ON UPDATE RESTRICT ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE trade (
    trade_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    housing_type VARCHAR(10) NOT NULL CHECK (housing_type IN ('APT', 'VILLA')),
    deal_category VARCHAR(10) NOT NULL CHECK (deal_category IN ('SALE', 'RENT')),
    rent_type VARCHAR(10),
    dataset_id VARCHAR(20) NOT NULL,
    sgg_cd VARCHAR(5) NOT NULL,
    legal_dong_cd VARCHAR(10),
    umd_nm VARCHAR(60),
    complex_id BIGINT UNSIGNED,
    building_name VARCHAR(100),
    jibun VARCHAR(20),
    road_address VARCHAR(200),
    exclu_use_area DECIMAL(6, 2) NOT NULL,
    floor SMALLINT,
    build_year SMALLINT,
    deal_date DATE NOT NULL,
    deal_amount BIGINT,
    deposit_amount BIGINT,
    monthly_rent_amount BIGINT,
    apt_dong VARCHAR(20),
    dealing_type VARCHAR(10),
    agent_sgg_nm VARCHAR(30),
    registration_date DATE,
    seller_type VARCHAR(10),
    buyer_type VARCHAR(10),
    land_lease_yn BOOLEAN,
    cancel_yn BOOLEAN NOT NULL,
    cancel_date DATE,
    match_method VARCHAR(12) CHECK (match_method IN ('EXACT', 'SIMILAR')),
    match_confidence DECIMAL(4, 3),
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    location_precision VARCHAR(10),
    dedup_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT fk_trade_legal_dong_cd FOREIGN KEY (legal_dong_cd)
        REFERENCES legal_district_code (legal_dong_cd) ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_trade_complex_id FOREIGN KEY (complex_id)
        REFERENCES complex (complex_id) ON UPDATE RESTRICT ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
