# application.properties
spring.application.name=homesense

spring.profiles.active=local

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=Asia/Seoul

# PORT
server.port=8080

# SQL
logging.level.com.homesense=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# BAT-SCH-01
homesense.batch.scheduler.housing-types=APT

# BAT-ERR-01
homesense.batch.retry.backoff-minutes=1,5,30
homesense.batch.retry.max-total-wait-minutes=180
